baseURL = "/"
languageCode = "de"
title = "IFGE"
author = "Leichtware GmbH"
uglyurls = false

[markup.goldmark.renderer]
unsafe = true

[params]
SiteDescription = "Beschreibung auf Site-Ebene als Fallback der einzelnen Pages"
