baseURL = "/"
title = "IFGE"
author = "Leichtware GmbH"

assetDir = "static"

languageCode = "de"
defaultContentLanguage = "de"
summaryLength = 30

[taxonomies]
tag = "tags"
category = "categories"

[markup.goldmark.renderer]
unsafe = true

[params]
rich_provider = "IFGE"
SiteDescription = "Als einziges Institut gibt es am IFGE den WKO zertifizierten Lehrgang für Lebens- und Sozialberatung immer wöchentlich an 3 Standorten (Wien, Burgenland & Niederösterreich) unter der Woche von 14:00 bis 20:00 Uhr  oder samstags von 10:00 bis 16:00 Uhr. Weitere WKO zertifizierte Upgrades wie \"Supervision\" und \"Aufstellungsarbeit\", sowie viele spannende Fortbildungen, finden auch an Wochenenden statt. Lernen in einer wertschätzenden und offenen Umgebung."
og_site_name = "IFGE - Wir vereinen Intuition, Fachwissen, Gefühl und Erfolg!"
og_image = "/img/startseite_handy.jpg"

[menu]

    [[menu.main]]
        name = "Übers IFGE"
        identifier = "IFGE"
        url = "#"
        weight = 1

    [[menu.main]]
        name = "Präsenz-Ausbildungen"
        identifier = "praesenz"
        url = "#"       
        weight = 2

    [[menu.main]]
        name = "Dipl. Ausbildungen"
        identifier = "diplomlehrgaenge"
        url = "#"       
        weight = 3
        parent = "praesenz"

    [[menu.main]]
        name = "Upgrades"
        identifier = "upgrade"
        url = "#"       
        weight = 4
        parent = "praesenz"

    [[menu.main]]
        name = "Fortbildungen"
        identifier = "fortb"
        url = "#"       
        weight = 4
        parent = "praesenz"

    [[menu.main]]
        name = "Online-Ausbildungen"
        identifier = "online"
        url = "#"
        weight = 5
    
    [[menu.main]]
        name = "Online-Akademie"
        identifier = "onlineakademie"
        url = "#"
        weight = 6

    [[menu.main]]
        name = "Supervision"
        identifier = "supervision"
        url = "#"
        weight = 7
    
    [[menu.main]]
        name = "Gruppenselbsterfahrung"
        identifier = "gruppenselbsterfahrung"
        url = "#"
        weight = 8

    [[menu.main]]
        name = "Psychosoziale Beratung"
        identifier = "psychologischeberatung"
        url = "#"
        weight = 9

    [[menu.main]]
        name = "Videos"
        url = "https://www.youtube.com/user/IFGEpodlisca/videos"
        weight = "10"
