baseURL = "/"
languageCode = "de"
title = "IFGE"
author = "Leichtware GmbH"
uglyurls = true

summaryLength = 30

[markup.goldmark.renderer]
unsafe = true

[params]
SiteDescription = "Als einziges Institut gibt es am IFGE den WKO zertifizierten Lehrgang für Lebens- und Sozialberatung immer wöchentlich an 3 Standorten (Wien, Burgenland & Niederösterreich) unter der Woche von 14:00 bis 20:00 Uhr  oder samstags von 10:00 bis 16:00 Uhr. Weitere WKO zertifizierte Upgrades wie \"Supervision\" und \"Aufstellungsarbeit\", sowie viele spannende Fortbildungen, finden auch an Wochenenden statt. Lernen in einer wertschätzenden und offenen Umgebung."

[menu]

    [[menu.main]]
        name = "Übers IFGE"
        identifier = "IFGE"
        url = "#"
        weight = 1

    [[menu.main]]
        name = "Ausbildungen"
        identifier = "ausb"
        url = "#"       
        weight = 2

    [[menu.main]]
        name = "Online-Ausbildungen"
        identifier = "online"
        url = "#"
        weight = 3
    
    [[menu.main]]
        name = "Supervision"
        identifier = "supervision"
        url = "#"
        weight = 4
    
    [[menu.main]]
        name = "Gruppenselbsterfahrung"
        identifier = "gruppenselbsterfahrung"
        url = "#"
        weight = 5
