baseURL = "/"
title = "IFGE"
author = "Leichtware GmbH"

assetDir = "static"

languageCode = "de"
defaultContentLanguage = "de"
summaryLength = 30

[taxonomies]
tag = "tags"
category = "categories"

[markup.goldmark.renderer]
unsafe = true

[params]
rich_provider = "IFGE"
SiteDescription = "Weiterbildung. Veränderung. Selbstverwirklichung. Das gehört zu einem erfüllten Leben dazu. Und genau das steht seit mehr als 20 Jahren im Zentrum unseres Instituts. Wir bewegen Menschen mit vielfältigen Qualitätsausbildungen, begleiten sie bei ihrer beruflichen sowie persönlichen Entwicklung und bereichern sie so mit neuen Perspektiven. Und das mit viel Intuition, fundiertem Fachwissen, jeder Menge Gefühl und großem Erfolg."
og_image = "/img/silvia_onlineakdademie.jpg"

[menu]

    [[menu.main]]
        name = "Übers IFGE"
        identifier = "IFGE"
        url = "#"
        weight = 1

    
    [[menu.main]]
        name = "Online-Akademie"
        identifier = "onlineakademie"
        url = "#"
        weight = 99
    
    [[menu.main]]
        name = "Supervision"
        identifier = "supervision"
        url = "#"
        weight = 3
    
    [[menu.main]]
        name = "Psychologische Beratung"
        identifier = "psychologischeberatung"
        url = "#"
        weight = 2
    
    [[menu.main]]
        name = "Einzelsetting"
        identifier = "psychologischeberatung_einzel"
        url = "#"
        weight = 10
        parent = "psychologischeberatung"
    
    [[menu.main]]
        name = "Gruppensetting"
        identifier = "psychologischeberatung_gruppe"
        url = "#"
        weight = 12
        parent = "psychologischeberatung"

    [[menu.main]]
    name = "Familienaufstellung: Termin online wählen"
    identifier = "familienaufstellung-termin"
    url = "/psychologische-beratung/gruppenselbsterfahrung/termine/"
    weight = 7

[[menu.main]]
identifier = "onlinebuchung"
name = "Onlinebuchung"
url = "/psychologische-beratung/onlinebuchung-beratung/"
weight = 6
class = "highlight-button"

